# 业务代码错误信息配置
# docs: https://github.com/nodeca/js-yaml

#  20502
#  2	05	02
#  服务级错误（1为系统级错误 2服务级错误 3其他错误，如第三方、硬件等）	服务模块代码	具体错误代码

# 1系统级
10001:	系统错误
10002:	服务暂停
10003:	远程服务错误
10004:	IP限制不能请求该资源
10005:	该资源需要appkey拥有授权
10006:	缺少source (appkey) 参数
10007:	不支持的MediaType (%s)
10008:	参数错误，请参考API文档
10009:	任务过多，系统繁忙
10010:	任务超时
10011:	RPC错误
10012:	非法请求
10013:	不合法的用户
10014:	应用的接口访问权限受限
10016:	缺失必选参数 (%s)，请参考API文档
10017:	参数值非法，需为 (%s)，实际为 (%s)，请参考API文档
10018:	请求长度超过限制
10020:	接口不存在
10021:	请求的HTTP METHOD不支持，请检查是否选择了正确的POST/GET方式
10022:	IP请求频次超过上限
10023:	用户请求频次超过上限
10024:	用户请求特殊接口 (%s) 频次超过上限

# 2服务级
# 2服务级-通用
20101: 用户名或密码不正确
20102: 用户名密码认证超过请求限制
20103: 缺少必要的参数
20104: 登录身份已过期 # accessToken
20105: 登录身份已过期 # refreshToken
20106: 验证码不正确
20107: 操作失败
20108: 验证码已失效
20109: 无效的token
20110: 用户会话可能已经被删除
20111: 用户可能已经被删除
20112: 用户密码可能已经被修改

# 2服务级-菜单权限
20201: 菜单必须包含父节点
20202: 未找到父节点
20203: 非法操作：该节点仅支持目录类型父节点
20204: 未找到节点

# 2服务级-操作权限
20301: 未找到操作

# 2服务级-角色
20401: 未找到角色

# 2服务级-用户
20501: 未找到用户
20502: 登录名已被注册

# 2服务级-在线用户
20601: 下线失败

# 2服务级-消息通知
20701: 未找到通知
